
# configs/chain_regret.yaml
# Reproduce Fig. 8: regret curves for N in {5,10,30,50}
episodes: 100000
#seeds: [0,1,2,3,4,5,6,7,8,9]   # ten seeds as in the paper
seeds: [1]
#seeds: [0]
#Ns: [5, 10, 30, 50]
Ns: [3,4,5]
#Ns: [3]
#algorithms: ["PSRL", "UCBVI-BF", "UCBVI-CH", "Q-Learning"]
algorithms: ["UCBVI-CH"]
ucbvi:
  delta: 1e-6
#q_learning:
#  alpha: 0.5
#  alpha_decay: 0.0
#  epsilon: 0.1
#  epsilon_decay: 0.0
#  min_epsilon: 0.0
plot_path: "outputs/figures/figure8_reproduction.png"
csv_prefix: "outputs/csv/fig8"
